### ISSUE TITLE
Seems to break with quotes

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-shellbot#6]
```
E, [2016-03-05T17:53:49.330497 #165] ERROR -- : Unmatched double quote: "And guys don't eat the pitch deck " (ArgumentError)
/app/vendor/ruby-2.2.4/lib/ruby/2.2.0/shellwords.rb:75:in `block in shellsplit'
/app/vendor/ruby-2.2.4/lib/ruby/2.2.0/shellwords.rb:73:in `scan'
/app/vendor/ruby-2.2.4/lib/ruby/2.2.0/shellwords.rb:73:in `shellsplit'
/app/config/initializers/slack-ruby-bot/hooks/message.rb:36:in `split_redirect'
/app/config/initializers/slack-ruby-bot/hooks/message.rb:12:in `message'
```

**Comment by dblock** [comment]
```
E, [2018-09-10T11:47:17.346035 #215] ERROR -- : Unmatched double quote: "@U02BAQ07B @U3UNN0FQT @UAX7JL5MJ ..." (ArgumentError)
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/shellwords.rb:83:in `block in shellsplit'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/shellwords.rb:81:in `scan'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/shellwords.rb:81:in `shellsplit'
/app/config/initializers/slack-ruby-bot/hooks/message.rb:35:in `split_redirect'
/app/config/initializers/slack-ruby-bot/hooks/message.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic-slack-ruby-bot-0.2.1/lib/newrelic-slack-ruby-bot/instrumentation.rb:25:in `block in message_with_new_relic'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.3.0.346/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:369:in `perform_action_with_newrelic_trace'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic-slack-ruby-bot-0.2.1/lib/newrelic-slack-ruby-bot/instrumentation.rb:21:in `message_with_new_relic'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/hooks/set.rb:33:in `block (2 levels) in register_callback'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/set.rb:306:in `each_key'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/set.rb:306:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-bot-0.11.1/lib/slack-ruby-bot/hooks/set.rb:32:in `block in register_callback'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.13.0/lib/slack/real_time/client.rb:199:in `block in run_callbacks'
```
